# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(992, 872)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    color:#fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color:#040f13;\n"
"}\n"
"#side_menu{\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton{\n"
"    padding:10px;\n"
"    background-color:#040f13;\n"
"    border-radius:5px;\n"
"}\n"
"#main_body{\n"
"    background-color:#071e26;\n"
"    border-radius:10px;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 50))
        self.header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.header)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menuButton = QtWidgets.QPushButton(self.frame)
        self.menuButton.setMinimumSize(QtCore.QSize(100, 30))
        self.menuButton.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.menuButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuButton.setIcon(icon)
        self.menuButton.setObjectName("menuButton")
        self.horizontalLayout_4.addWidget(self.menuButton)
        self.horizontalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.frame_3 = QtWidgets.QFrame(self.header)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logo = QtWidgets.QPushButton(self.frame_3)
        self.logo.setMaximumSize(QtCore.QSize(50, 50))
        self.logo.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/pepe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logo.setIcon(icon1)
        self.logo.setIconSize(QtCore.QSize(50, 50))
        self.logo.setObjectName("logo")
        self.horizontalLayout_3.addWidget(self.logo)
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Brianne\'s hand")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.header)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu = QtWidgets.QWidget(self.frame_2)
        self.side_menu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.side_menu.setStyleSheet("")
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_menu)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.side_menu)
        self.frame_4.setMinimumSize(QtCore.QSize(150, 400))
        self.frame_4.setMaximumSize(QtCore.QSize(600, 1000))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Automatic_button = QtWidgets.QPushButton(self.frame_4)
        self.Automatic_button.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Automatic_button.setFont(font)
        self.Automatic_button.setStyleSheet("QPushButton:hover:!pressed {\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #c471f5, stop: 1 #fa71cd );\n"
"}")
        self.Automatic_button.setObjectName("Automatic_button")
        self.verticalLayout_3.addWidget(self.Automatic_button)
        self.AutoWidget = QtWidgets.QWidget(self.frame_4)
        self.AutoWidget.setMaximumSize(QtCore.QSize(150, 150))
        self.AutoWidget.setObjectName("AutoWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.AutoWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rectangle_label = QtWidgets.QLabel(self.AutoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rectangle_label.sizePolicy().hasHeightForWidth())
        self.rectangle_label.setSizePolicy(sizePolicy)
        self.rectangle_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.rectangle_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rectangle_label.setObjectName("rectangle_label")
        self.verticalLayout_4.addWidget(self.rectangle_label)
        self.combO_box = QtWidgets.QCheckBox(self.AutoWidget)
        self.combO_box.setObjectName("combO_box")
        self.verticalLayout_4.addWidget(self.combO_box)
        self.combN_box = QtWidgets.QCheckBox(self.AutoWidget)
        self.combN_box.setObjectName("combN_box")
        self.verticalLayout_4.addWidget(self.combN_box)
        self.range_label = QtWidgets.QLabel(self.AutoWidget)
        self.range_label.setMaximumSize(QtCore.QSize(150, 20))
        self.range_label.setObjectName("range_label")
        self.verticalLayout_4.addWidget(self.range_label)
        self.rangeSlider = QtWidgets.QSlider(self.AutoWidget)
        self.rangeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rangeSlider.setObjectName("rangeSlider")
        self.verticalLayout_4.addWidget(self.rangeSlider)
        self.verticalLayout_3.addWidget(self.AutoWidget)
        self.Settings_button = QtWidgets.QPushButton(self.frame_4)
        self.Settings_button.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Settings_button.setFont(font)
        self.Settings_button.setStyleSheet("QPushButton:hover:!pressed {\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #c471f5, stop: 1 #fa71cd );\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Settings_button.setIcon(icon2)
        self.Settings_button.setObjectName("Settings_button")
        self.verticalLayout_3.addWidget(self.Settings_button)
        self.settings_widget = QtWidgets.QWidget(self.frame_4)
        self.settings_widget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.settings_widget.setObjectName("settings_widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.settings_widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sort_box = QtWidgets.QCheckBox(self.settings_widget)
        self.sort_box.setObjectName("sort_box")
        self.verticalLayout_6.addWidget(self.sort_box)
        self.translator_label = QtWidgets.QLabel(self.settings_widget)
        self.translator_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.translator_label.setObjectName("translator_label")
        self.verticalLayout_6.addWidget(self.translator_label)
        self.translateOptions = QtWidgets.QComboBox(self.settings_widget)
        self.translateOptions.setMaximumSize(QtCore.QSize(16777215, 20))
        self.translateOptions.setStyleSheet("QComboBox {\n"
"    border-color: rgb(85, 170, 255);\n"
"}\n"
"\n"
"QComboBox::on {\n"
"    border: 2px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: 0px;\n"
"}\n"
"\n"
"QComboBox QListView {\n"
"    border-style: none;\n"
"    background-color: black;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/Icons/down-chevron.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}")
        self.translateOptions.setObjectName("translateOptions")
        self.translateOptions.addItem("")
        self.translateOptions.addItem("")
        self.translateOptions.addItem("")
        self.verticalLayout_6.addWidget(self.translateOptions)
        self.label_5 = QtWidgets.QLabel(self.settings_widget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.comboBox_3 = QtWidgets.QComboBox(self.settings_widget)
        self.comboBox_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"    border-color: rgb(85, 170, 255);\n"
"}\n"
"\n"
"QComboBox::on {\n"
"    border: 2px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: 0px;\n"
"}\n"
"\n"
"QComboBox QListView {\n"
"    border-style: none;\n"
"    background-color: black;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/Icons/down-chevron.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox_3)
        self.Advance_setting_button = QtWidgets.QPushButton(self.settings_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Advance_setting_button.setFont(font)
        self.Advance_setting_button.setStyleSheet("QPushButton:hover:!pressed {\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #c471f5, stop: 1 #fa71cd );\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/advance.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Advance_setting_button.setIcon(icon3)
        self.Advance_setting_button.setObjectName("Advance_setting_button")
        self.verticalLayout_6.addWidget(self.Advance_setting_button)
        self.verticalLayout_3.addWidget(self.settings_widget)
        self.verticalLayout_2.addWidget(self.frame_4, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 500, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.side_menu)
        self.main_body = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body.sizePolicy().hasHeightForWidth())
        self.main_body.setSizePolicy(sizePolicy)
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.imageDisplay = QtWidgets.QHBoxLayout()
        self.imageDisplay.setObjectName("imageDisplay")
        
        self.leftArrow = QtWidgets.QPushButton(self.main_body)
        self.leftArrow.setMaximumSize(QtCore.QSize(70, 90))
        self.leftArrow.setStyleSheet("QPushButton {\n"
"    height: 90;\n"
"    width: 70;\n"
"    border-radius: 25px;\n"
"    padding: 10px;\n"
"    background-color: #040f13;\n"
"}\n"
"QPushButton:hover:!pressed {\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #c471f5, stop: 1 #fa71cd );\n"
"}")
        self.leftArrow.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/play1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftArrow.setIcon(icon4)
        self.leftArrow.setObjectName("leftArrow")
        self.imageDisplay.addWidget(self.leftArrow)
        self.imageWidget = QtWidgets.QWidget(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageWidget.sizePolicy().hasHeightForWidth())
        self.imageWidget.setSizePolicy(sizePolicy)
        self.imageWidget.setMaximumSize(QtCore.QSize(400, 300))
        self.imageWidget.setStyleSheet("background-color: #040f13;\n"
"border-radius: 10px")
        self.imageWidget.setObjectName("imageWidget")
        self.imageDisplay.addWidget(self.imageWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.imageWidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rightArrow = QtWidgets.QPushButton(self.main_body)
        self.rightArrow.setMaximumSize(QtCore.QSize(70, 90))
        self.rightArrow.setStyleSheet("QPushButton {\n"
"    height: 90;\n"
"    width: 70;\n"
"    border-radius: 25px;\n"
"    padding: 10px;\n"
"    background-color: #040f13;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #c471f5, stop: 1 #fa71cd );\n"
"}")
        self.rightArrow.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightArrow.setIcon(icon5)
        self.rightArrow.setObjectName("rightArrow")
        self.imageDisplay.addWidget(self.rightArrow)
        self.imageDisplay.setStretch(0, 1)
        self.imageDisplay.setStretch(1, 1)
        self.imageDisplay.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.imageDisplay)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.progressBar = QtWidgets.QProgressBar(self.main_body)
        self.progressBar.setMinimumSize(QtCore.QSize(200, 20))
        self.progressBar.setMaximumSize(QtCore.QSize(200, 20))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 2px solid #3F51B5;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #3F51B5;\n"
"    width: 10px;\n"
"    margin: 0.5px;\n"
"    border-radius:1px;\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_7.addWidget(self.progressBar, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.actionsButtons = QtWidgets.QHBoxLayout()
        self.actionsButtons.setContentsMargins(-1, -1, 1, 1)
        self.actionsButtons.setSpacing(0)
        self.actionsButtons.setObjectName("actionsButtons")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.actionsButtons.addItem(spacerItem1)
        self.clearButton = QtWidgets.QPushButton(self.main_body)
        self.clearButton.setMinimumSize(QtCore.QSize(130, 45))
        self.clearButton.setMaximumSize(QtCore.QSize(130, 45))
        self.clearButton.setStyleSheet("QPushButton {\n"
"    height: 20;\n"
"    width: 30;\n"
"    border-radius: 7px;\n"
"    padding: 10px;\n"
"    background-color: #040f13;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #c471f5, stop: 1 #fa71cd );\n"
"}")
        self.clearButton.setObjectName("clearButton")
        self.actionsButtons.addWidget(self.clearButton)
        self.upload = QtWidgets.QPushButton(self.main_body)
        self.upload.setMinimumSize(QtCore.QSize(130, 45))
        self.upload.setMaximumSize(QtCore.QSize(130, 45))
        self.upload.setStyleSheet("QPushButton {\n"
"    height: 20;\n"
"    width: 30;\n"
"    border-radius: 7px;\n"
"    padding: 10px;\n"
"    background-color: #040f13;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #c471f5, stop: 1 #fa71cd );\n"
"}")
        self.upload.setObjectName("upload")
        self.actionsButtons.addWidget(self.upload)
        self.translate = QtWidgets.QPushButton(self.main_body)
        self.translate.setMinimumSize(QtCore.QSize(130, 45))
        self.translate.setMaximumSize(QtCore.QSize(130, 45))
        self.translate.setStyleSheet("QPushButton {\n"
"    height: 20;\n"
"    width: 30;\n"
"    border-radius: 7px;\n"
"    padding: 10px;\n"
"    background-color: #040f13;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #c471f5, stop: 1 #fa71cd );\n"
"}")
        self.translate.setObjectName("translate")
        self.actionsButtons.addWidget(self.translate)
        self.saveButton = QtWidgets.QPushButton(self.main_body)
        self.saveButton.setMinimumSize(QtCore.QSize(130, 45))
        self.saveButton.setMaximumSize(QtCore.QSize(130, 45))
        self.saveButton.setStyleSheet("QPushButton {\n"
"    height: 20;\n"
"    width: 30;\n"
"    border-radius: 7px;\n"
"    padding: 10px;\n"
"    background-color: #040f13;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #c471f5, stop: 1 #fa71cd );\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.actionsButtons.addWidget(self.saveButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.actionsButtons.addItem(spacerItem2)
        self.actionsButtons.setStretch(1, 1)
        self.actionsButtons.setStretch(2, 1)
        self.verticalLayout_7.addLayout(self.actionsButtons)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout.addWidget(self.main_body)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuButton.setText(_translate("MainWindow", "MENU"))
        self.label.setText(_translate("MainWindow", "Test"))
        self.Automatic_button.setText(_translate("MainWindow", "Automatic"))
        self.rectangle_label.setText(_translate("MainWindow", "Rectangle"))
        self.combO_box.setText(_translate("MainWindow", "CombineOverlap"))
        self.combN_box.setText(_translate("MainWindow", "CombineNeighbors"))
        self.range_label.setText(_translate("MainWindow", "Range"))
        self.Settings_button.setText(_translate("MainWindow", "Settings"))
        self.sort_box.setText(_translate("MainWindow", "Sort pages by file name"))
        self.translator_label.setText(_translate("MainWindow", "Translator:"))
        self.translateOptions.setItemText(0, _translate("MainWindow", "Bing"))
        self.translateOptions.setItemText(1, _translate("MainWindow", "Google"))
        self.translateOptions.setItemText(2, _translate("MainWindow", "DeepL"))
        self.label_5.setText(_translate("MainWindow", "From Language:"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Japanese"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Korean"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Chinese"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Auto Detect"))
        self.Advance_setting_button.setText(_translate("MainWindow", "Advanced Setting"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.upload.setText(_translate("MainWindow", "Upload"))
        self.translate.setText(_translate("MainWindow", "Translate"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
